# Generated by Django 3.1 on 2020-08-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='movie/images/')),
                ('Time', models.IntegerField()),
                ('Language', models.CharField(max_length=250)),
                ('Rating', models.FloatField(default=0)),
                ('Director', models.CharField(max_length=250)),
                ('Country', models.CharField(max_length=250)),
                ('Jenre', models.CharField(max_length=250)),
                ('Cinematography', models.CharField(blank=True, max_length=250)),
                ('Screenplay', models.CharField(blank=True, max_length=250)),
                ('Music', models.CharField(blank=True, max_length=250)),
                ('Year', models.IntegerField()),
                ('Cast', models.TextField()),
                ('Synopsis', models.TextField()),
                ('IsMovieOfDay', models.BooleanField(default=False)),
            ],
        ),
    ]
