# Generated by Django 3.1 on 2020-08-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_comment_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='DateAdded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
