# Generated by Django 3.1 on 2020-08-31 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20200826_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='FirstDownloadLink',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='SecondDownloadLink',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='SmallImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='movie/images/'),
            preserve_default=False,
        ),
    ]
