# Generated by Django 3.1 on 2020-08-31 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20200831_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='SubtitleLink',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='Writer',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
