# Generated by Django 3.1 on 2020-09-01 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20200831_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='SmallImage',
            new_name='FilmBackgroundImage',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='FilmOfTheDayImage',
        ),
        migrations.AddField(
            model_name='movie',
            name='BoxFilmImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='movie/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='SmallBoxFilmImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='movie/images/'),
            preserve_default=False,
        ),
    ]
