# Generated by Django 3.1 on 2020-09-01 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20200901_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='FilmOfTheDaySmallImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='movie/images/'),
            preserve_default=False,
        ),
    ]
